set init_layout_view ""
set init_abstract_name ""
#set init_verilog "./filter_io.sv"
set init_verilog "./INPUT_DATA/network_io.sv"
set init_mmmc_file "./view_definition.tcl"
set init_lef_file "/softslin/AMS_410_ISR15/cds/HK_C35/LEF/c35b4/c35b4.lef /softslin/AMS_410_ISR15/cds/HK_C35/LEF/c35b4/CORELIB.lef /softslin/AMS_410_ISR15/cds/HK_C35/LEF/c35b4/IOLIB_4M.lef"
set init_top_cell "network_io"
set init_gnd_net "gnd! gnd3r! gnd3o!"
set init_pwr_net "vdd! vdd3r1! vdd3r2! vdd3o!"

